//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesignPatternAssignment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Air
    {
        public int AirId { get; set; }
        public string AirName { get; set; }
        public string AirFromCity { get; set; }
        public string AirToCity { get; set; }
        public string AirClass { get; set; }
        public string IsSaved { get; set; }
        public string IsBooked { get; set; }
        public int AirPrice { get; set; }
    }
}
