//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesignPatternAssignment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel
    {
        public int HotelId { get; set; }
        public string HotelName { get; set; }
        public string HotelCity { get; set; }
        public int HotelAvailableRooms { get; set; }
        public string IsSaved { get; set; }
        public string IsBooked { get; set; }
        public string HotelRoomType { get; set; }
        public int HotelPrice { get; set; }
    }
}
